### ISSUE TITLE
Address github action warnings

### ISSUE THREAD

**Issue by coderofstuff** [kaspanet/rusty-kaspa#469]
# Description
GitHub action pipeline runs currently display these warnings:

<img width="1150" alt="Screenshot 2024-05-05 at 12 11 58 PM" src="https://github.com/kaspanet/rusty-kaspa/assets/114628839/afcf5551-c1d7-4deb-b343-cc17c2d778a7">

# TODO
- [ ] Fix the warnings in the pipelines by following the recommended actions in these warnings. Example pipeline run: https://github.com/kaspanet/rusty-kaspa/actions/runs/8893079535

**Comment by KaffinPX** [comment]
@aspect what about using Bun for it? its way faster at least when installing packages(on Kaspian its seconds to have a build after a commit).

**Comment by aspect** [comment]
> @aspect what about using Bun for it? its way faster at least when installing packages and no need for installing TypeScript externally(on Kaspian its seconds to have a build after a commit).

I unfortunately don’t have bandwidth to deal with bun right now. + NodeJs is used to build node_modules as a part of the WASM SDK release process as well as run a small node script after the build (to add size data to example folders).

This issue is a simple CI update that should for the most part require just updating package versions. It is kept for someone who knows CI and wants to get their hands dirty to contribute to the project.

**Comment by coderofstuff** [comment]
Addressed by https://github.com/kaspanet/rusty-kaspa/pull/471
