### ISSUE TITLE
Can't send kaspa out of kaspa-ng

### ISSUE THREAD

**Issue by Jinxsyns** [kaspanet/rusty-kaspa#497]
**Describe the bug**
For some reason it say's I have insufficient funds even when I put in significantly less that what I have in the wallet

**To Reproduce**
All I did was input a destination address and go to input the amount I roughly have (so fees can be removed from the remainder of the dust leftover) and it says insufficient funds and won't let me send it.

**Expected behavior**
Being able to send the funds

**Screenshots**
![Screenshot 2024-06-29 212128](https://github.com/kaspanet/rusty-kaspa/assets/130711085/a4ed1748-27df-4749-b73a-d658528cc2dc)
![Screenshot 2024-06-29 212330](https://github.com/kaspanet/rusty-kaspa/assets/130711085/aab4175c-7bb4-4453-ae7b-9062ecfed2f7)

**Desktop (please complete the following information):**
 - OS: windows 11 home vs. 10.0.22631 build 22631
 - Kaspad version: kaspa NG v0.2.5-eac0efa + Rusty Kaspa v0.14.1

**Additional context**

**Comment by Jinxsyns** [comment]
oh additional context. yes the wallet is fully synced.

**Comment by Jinxsyns** [comment]
apparently It works on the remote kaspa node. but not on the integrated daemon

**Comment by Jinxsyns** [comment]
Nevermind it's throwing an error trying to decrypt the wallet 
![Screenshot 2024-06-30 053321](https://github.com/kaspanet/rusty-kaspa/assets/130711085/9c2b9516-b359-4c16-8f2a-cb1d0fbb094c)

**Comment by Jinxsyns** [comment]
I was initially using the wrong bip39 phrase realized my error fixed it and it still won't decrypt the wallet

**Comment by Jinxsyns** [comment]
I apologize for so many replies I'm just stubborn and still trying things. apparently I still had the bip39 phrase wrong fixed it and it worked on the remote node but I still couldn't get it to allow me to press the send button to get to the point of being able to input the password and bip39 phrase to decrypt the wallet for the transaction on the integrated daemon

**Comment by aspect** [comment]
This is not a `kaspa-ng` repository.  Please use https://github.com/aspectron/kaspa-ng/issues to file kaspa-ng related issues.

The "insufficient balance" issue has been fixed at https://kaspa-ng.org and the update for the desktop version is available here:

https://github.com/aspectron/kaspa-ng/releases/tag/v0.2.6-pre-rc1

Decryption problems occur due to incorrect passphrases during creation or subsequent attempts to access the wallet.  If the bip39 passphrase is incorrect, nothing can be done to recover the wallet.  If the wallet passphrase is incorrect, one can use the mnemonic to recover the wallet.
