### ISSUE TITLE
wasm can't get address from ECDSA public key

### ISSUE THREAD

**Issue by drunkirishcoder** [kaspanet/rusty-kaspa#536]
**Describe the bug**
Unable to get the ECDSA address from a public key. works with a private key, but does not work if you direct get it by using a public key.

**To Reproduce**

```
const publicKey = new PublicKey('...'); 
publicKey.toAddressECDSA(NetworkType.Mainnet).toString()
```

the code will panic

problem appears to be [here](https://github.com/kaspanet/rusty-kaspa/blob/6a56461ff1249e11e3124090253ca0bf128f7189/wallet/keys/src/publickey.rs#L84). instead using `xonly_public_key`, it should try use `self.public_key`.

**Comment by aspect** [comment]
@drunkirishcoder thanks for reporting this. The next drink is on me!

- Fixed in https://github.com/kaspanet/rusty-kaspa/pull/538/commits/8eb7500f9517f456df7d5c44673b82633ff35e31
- Merged into https://github.com/kaspanet/rusty-kaspa/tree/dev
- WASM SDK artifact can be obtained from https://github.com/kaspanet/rusty-kaspa/actions/runs/10672898810

Cheers!

**Comment by drunkirishcoder** [comment]
thank you
